import Head from 'next/head'
import ImageGenerator from "./components/girlGenerator";
import styles from '../styles/ImageGenerator.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Girl generator</title>
        <meta name="description" content="Generated by my dick" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       girl generator

       <ImageGenerator />
      </main>
    </div>
  )
}
